name: match head ref to configured list
on:
  - workflow_dispatch

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      name: ${{steps.name.outputs.value}}
    steps:
      - name: "match ref to configured pattern, outputting pattern within"
        id: name
        run: echo "value=$(grep -ioE $pattern <<< $target)" >> $GITHUB_OUTPUT
        env:
          pattern: ${{vars.REF_PATTERN}}
          target: ${{github.head_ref||github.ref}}

      - if: ${{ '' == steps.name.outputs.value || failure() }}
        name: fail empty pattern match
        run: |
          echo "pattern match failed" >> $GITHUB_STEP_SUMMARY
          exit 1

  validate:
    runs-on: ubuntu-latest
    needs: environment
    if: ${{ success() }}
    environment:
      name: ${{needs.environment.outputs.name}}
    steps:
      - name: summary
        run: echo "matched environment ${{vars.ENV_NAME}}" >> $GITHUB_STEP_SUMMARY
