name: match head ref to configured list
on:
  - workflow_dispatch

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      name: ${{steps.name.outputs.value}}
    env:
      pattern: ${{vars.REF_PATTERN}}
      ref: ${{github.head_ref||github.ref}}
    steps:
      - name: "match ref to configured pattern, outputting pattern within"
        id: name
        run: echo "value=$(egrep -io $pattern <<< $ref)" >> $GITHUB_OUTPUT

      - if: ${{ '' == steps.name.outputs.value || failure() }}
        run: |
          echo "# Pattern match failed" >> $GITHUB_STEP_SUMMARY
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "* \"${{ steps.name.outputs.value }}\"" >> $GITHUB_STEP_SUMMARY
          echo "## Input" >> $GITHUB_STEP_SUMMARY
          echo "* pattern: \"$pattern\"" >> $GITHUB_STEP_SUMMARY
          echo "* ref:     \"$ref\"" >> $GITHUB_STEP_SUMMARY
          exit 1

  validate:
    runs-on: ubuntu-latest
    needs: environment
    if: ${{ success() }}
    environment:
      name: ${{needs.environment.outputs.name}}
    steps:
      - name: summary
        run: echo "matched environment ${{vars.ENV_NAME}}" >> $GITHUB_STEP_SUMMARY
