name: "describe tag event"
on:
  push:
    tags:
      - "*"
jobs:
  describe:
    runs-on:  ubuntu@latest
    steps:
      - name: jq event object
        run: |
          jq '.' <<< "${{ github.event }}"
