name: "describe tag event"
on:
  push:
    tags:
      - "*"
jobs:
  describe:
    runs-on:  ubuntu-latest
    steps:
      - name: jq github object data
        run: |
          echo "github.event --"; jq '.' <<< "${{github.event}}"
          echo "github.ref --"; jq '.' <<< "${{github.ref}}"
          echo "github.ref_name --"; jq '.' <<< "${{github.ref_name}}"
          echo "github.sha --"; jq '.' <<< "${{github.sha}}"

