name: "[Pre]Release created"
on:
  release:
    types: ['released', 'prereleased']
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "published_at ${{ github.event.release.published_at }}"
          echo "draft ${{ github.event.release.draft }}"
          echo "prerelease ${{ github.event.release.prerelease }}"
          echo "name ${{ github.event.release.name }}"